# Spring properties
spring:
  application:
     name: service1

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

# HTTP Server
server:
  port: 9091   # HTTP (Tomcat) port
  
  
info:
  app: 
   name: Spring Actuator Example
   
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

    

    